# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Sangche very initial's Blog
tagline:          ""
url:              http://sangche.github.io
paginate:         1
baseurl:          /
author:
  name:           Sangche
  url:            http://google.com

gems:
  - jekyll-sitemap
